### ISSUE TITLE
Two minor issues that are right up your ally

### ISSUE THREAD

**Issue by micmou** [jss2a98aj/Starbound-Patch-Project#11]
There are two items that have some minor issues that would be perfect for the patch project.

The Mutagen Pipe back item doesnt have walk backwards frames... It just vanishes when you hold anything aimable and walk backwards.

The Voyage Chestpieces shoulders rotate funkily with the arms.

Item Name for both objects
mutantback
voyagerchest

**Comment by jss2a98aj** [comment]
The Mutagen Back Pipe is fixed in update 1.4.0 The other issue is not possible to fix without changing the look of the armor.
