### ISSUE TITLE
Does this fix some memory leaks like the pixel printer?

### ISSUE THREAD

**Issue by Shadowblitz16** [jss2a98aj/Starbound-Patch-Project#26]

**Comment by jss2a98aj** [comment]
The pixel printer does not leak memory. It can cause temporary lag when its interface is opened though.
I can suggest [Lagless Pixel Printer](https://steamcommunity.com/sharedfiles/filedetails/?id=3003880924) if the lag is enough of a problem in your setup. The other mod I am aware of that tries to improve the situation causes excessive log errors.
