### ISSUE TITLE
random fountains

### ISSUE THREAD

**Issue by lunapanshiel** [jss2a98aj/Starbound-Patch-Project#4]
this was something that's been broken for a long time, but the random fountain object, which can legitimately be bought from oasis merchants, uses old status pod code and was broken when the control script for status pods was adjusted. 

i made this little fix a while ago, which simply adds a sound effect to the fountain(yes that's all it needed) and culled some old, broken status effects from it's list

https://community.playstarbound.com/resources/random-fountain-fix.4883/ 

and would like to see it included in the project

**Comment by jss2a98aj** [comment]
Nice, I don't think I would have ever noticed that myself. I will add you to the credits and implement the fixes.
